### ISSUE TITLE
Broken on 12.7.2

### ISSUE THREAD

**Issue by scalp42** [chef/knife-push#34]
```
INFO: Using configuration from /Users/scalp/.chef/knife.rb
/Users/scalp/.rvm/gems/ruby-2.2.4@chef/bundler/gems/knife-push-21bf51560993/lib/chef/knife/job_list.rb:24:in `run': uninitialized constant Chef::REST (NameError)
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `load'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `<main>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `eval'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `<main>'
```

cc @manderson26

**Comment by martinisoft** [comment]
Can confirm this is an issue for me as well with the latest ChefDK

```
chef exec knife job list -VV
INFO: Using configuration from /Users/martinisoft/.chef/knife.rb
/Users/martinisoft/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.5.2/lib/chef/knife/job_list.rb:24:in `run': uninitialized constant Chef::REST (NameError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:50:in `load'
        from /opt/chefdk/bin/knife:50:in `<main>'
```

**Comment by martinisoft** [comment]
I have sent in a pull request though I have not checked for patch compatibility with previous chef versions.

**Comment by scalp42** [comment]
thanks @martinisoft :+1:

**Comment by UnbounDev** [comment]
This is still causing an undefined `rest` error for me using a fresh install of the ChefDK and fresh install of knife-push

```
INFO: Using configuration from /Users/austin/chef/chef-repo/.chef/knife.rb
/Users/austin/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.9.1/lib/chef/knife/job_helpers.rb:95:in `run_helper': undefined local variable or method `rest' for Chef::Knife::JobHelpers:Module (NameError)
	from /Users/austin/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.9.1/lib/chef/knife/job_start.rb:106:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:50:in `load'
	from /opt/chefdk/bin/knife:50:in `<main>'
```

knife-push:
```
$ gem list | grep knife-push
knife-push (0.9.1)
```

ChefDk:
```
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

$ knife -v
Chef: 12.7.2
```

ChefDk packaged ruby:
```
$ which ruby
/opt/chefdk/embedded/bin/ruby
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin12.0]
```
