### ISSUE TITLE
NameError: uninitialized constant Chef::Knife::JobStart::JobHelpers

### ISSUE THREAD

**Issue by scalp42** [chef/knife-push#36]
Using master and newest Chef:

```
$> bundle list | egrep "push|chef \("                                                                                                   
  * chef (12.8.1)
  * knife-push (0.9.1 925367f)

$> > knife job start unlock -s 'chef_environment:*' --timeout  30000 --quorum 1%
ERROR: knife encountered an unexpected error
This may be a bug in the 'job start' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: uninitialized constant Chef::Knife::JobStart::JobHelpers

INFO: Using configuration from /Users/scalp/.chef/knife.rb
/Users/scalp/.rvm/gems/ruby-2.2.4@chef/bundler/gems/knife-push-925367ffa187/lib/chef/knife/job_start.rb:92:in `run': uninitialized constant Chef::Knife::JobStart::JobHelpers (NameError)
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `load'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `<main>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `eval'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by scalp42** [comment]
@martinisoft or @thommay maybe :pray: ?

**Comment by lamont-granquist** [comment]
JobHelpers is a module that is exporting class methods and doesn’t inherit from Chef::Knife so it has no `def rest`

could inject the rest object from the code into the JobHelper call (changing the shape of that API).  could mix the JobHelpers directly into the Chef::Knife classes so that they have access to `def rest`.  Could bake in a call to get a Chef::ServerAPI object directly in the JobHelper (which will likely break old Chef 11 clients?).

**Comment by martinisoft** [comment]
@lamont-granquist Which of those three solutions seems like the best option then?

**Comment by lamont-granquist** [comment]
i don't know, that would be the next step.
