### ISSUE TITLE
uninitialized constant Chef::Rest (NameError)

### ISSUE THREAD

**Issue by spuder** [chef/knife-push#41]
## Problem

Fresh install of knife push jobs causes crash

## Error

Exception: NameError: uninitialized constant Chef::REST

## Step to Reproduce

```bash
hub clone chef/knife-push
rake install

knife job list
ERROR: knife encountered an unexpected error
This may be a bug in the 'job list' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: uninitialized constant Chef::REST

knife job list -VV
INFO: Using configuration from /Users/sowen/.chef/knife.rb
/Users/sowen/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.5.2/lib/chef/knife/job_list.rb:24:in `run': uninitialized constant Chef::REST (NameError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:49:in `load'
	from /opt/chefdk/bin/knife:49:in `<main>'
```

**Comment by spuder** [comment]
Friendly help in the IRC pointed out that this is available in the latest ruby gem which is currently in "pre"

Anyone else encountering this, install from the prerelease of the ruby gems. 

    chef gem install knife-push --pre

or

    sudo chef gem install knife-push --pre
